diffplug/selfie

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Literals.kt
selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/LiteralIntTest.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InlineIntTest.kt

- breakup long integers 1_000 not 1000, 1_000_000 not 1000000

Int Literal: encode long integers

---

docs/src/pages/jvm/get-started.mdx
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Mode.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/CommentTracker.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SnapshotStorage.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SourceFile.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
selfie-lib/src/jsMain/kotlin/com/diffplug/selfie/guts/CommentTracker.js.kt
selfie-lib/src/jsMain/kotlin/com/diffplug/selfie/guts/WriteTracker.js.kt
selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/CommentTracker.jvm.kt
selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/WriteTracker.jvm.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotFileLayoutJUnit5.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/DiskBasicTest.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/DiskTodoTest.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/Harness.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InteractiveTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_DiskBasicTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_DiskTodoTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_InteractiveTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_ReadWriteTest.ss

- implement #74
Still need to do:

Implement the `interactive` mode

---

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/KotlinMultilineString.kt
selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralStringTest.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/StringLiteralsKotlinTest.kt
undertest-junit5/src/test/java/undertest/junit5/UT_StringLiteralsJavaTest.java
undertest-junit5/src/test/kotlin/undertest/junit5/UT_StringLiteralsKotlinTest.kt

Kotlin's $ escaping made this a bit tricky. Groovy is very similar but a teensy bit different, we should update that.

Add support for Kotlin multiline (and single line) literals

---

selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieSettingsAPI.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotFileLayoutJUnit5.kt

While creating the advanced documentation, bumped into a few problems
- SelfieSettingsAPI javadoc had some shortcomings
- if you had any errors during settings initialization, those errors were kinda swallowed and hard to find.
In this PR, the docs are much-improved, and initialization errors are smuggled and rethrown in every snapshot assertion so that users can more easily find and fix the root cause.

Improve JUnit5's settings

---

docs/src/components/HeadingPopout.tsx
docs/src/components/Icons/Popout.tsx
docs/src/components/Navigation/SubNavigation.tsx
docs/src/components/mdx.tsx

- Popout styles should look like other unpressed buttons
- Shrink heading font size at mobile screen widths to fit
- Let long inline `<code>` elements reflow to new lines

Fine tune styles

---

docs/src/components/FooterCTA/FooterCTA.tsx

#100 
Issue can be reproduced more simply by:
1. "Hard" navigating to any route other than the landing page (either type in the URL or press the browser refresh button)
2. "Soft" navigating to the landing page by using the "why" link in the app itself (Next.js client-side navigation)
3. Scrolling down
The "resize" event isn't being called after a client-side navigation event. Solution is to make sure the `imageHeight` is set in the scroll event handler.

Fix landing page CTA bug

---

CHANGELOG.md
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotFileLayoutJUnit5.kt

- We started smuggling errors from initialization in #94
- Now we smuggle errors from `TestExecutionListener` too

Smuggle errors from `TestExecutionListener`

---

jvm/example-junit5/src/test/java/com/example/DemoGif.java
jvm/example-junit5/src/test/java/selfie/SelfieSettings.java
selfie.dev/public/robots.txt
selfie.dev/src/components/HeroGifDemo.tsx
selfie.dev/src/pages/_app.tsx
selfie.dev/src/pages/gif-demo/index.mdx
selfie.dev/src/pages/jvm/index.mdx

The reason it was worth creating selfie instead of using an existing snapshot library is because of facets. You can use them for lots of things, but the thing which is easiest to describe is "snapshot html to disk, render its md as inline snapshot".
To show that, we need a page to snapshot. Our landing page is the obvious candidate, but it has so much text that it confused the example.
This PR introduces a new page, `https://selfie.dev/gif-demo` which is basically the landing page without the content.

Add a route to selfie.dev for the gif demo.

---

selfie.dev/package.json
selfie.dev/public/_redirects
selfie.dev/src/pages/_app.tsx

Instead of redirecting `/` to `/jvm`, we'll render `/` as a copy of `/jvm`, but with 
- `<link rel="canonical" href="https://selfie.dev/jvm"/>`

Fix google search console errors

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/CommentTracker.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SnapshotStorage.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
jvm/selfie-lib/src/jsMain/kotlin/com/diffplug/selfie/guts/SnapshotStorage.js.kt
jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/SnapshotStorage.jvm.kt
jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/WriteTracker.jvm.kt
jvm/selfie-lib/src/jvmTest/kotlin/testpkg/RecordCallTest.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieGC.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotFileLayoutJUnit5.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotStorageJUnit5.kt

In the `guts` package we had a `Path` class which was a `java.io.File` in the JVM and a `String` in JS. This was extremely confusing.
`Path` has been replaced by `TypedPath`, which is just a `String absolutePath` where a trailing slash is used to signify that the path is or isn't a folder. This makes a lot of the "path math" we do easier and cheaper.
Note that this is technically a breaking change to the public API of the `lib` package, but the `guts` package is meant to be private.

Introduce `TypedPath`

---

jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieSuspend.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SnapshotSystem.kt
jvm/selfie-runner-junit5/build.gradle
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieExtension.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotSystemJUnit5.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SelfieExtension.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SnapshotSystemKotest.kt
jvm/undertest-junit5-kotest/src/test/kotlin/undertest/junit5/JunitKotestProjectConfig.kt
jvm/undertest-junit5-kotest/src/test/kotlin/undertest/junit5/UT_KotestConcurrencyStressTest.kt
jvm/undertest-junit5-kotest/src/test/kotlin/undertest/junit5/UT_KotestFunSpecTest.kt
jvm/undertest-junit5-kotest/src/test/kotlin/undertest/junit5/UT_KotestStringSpecTest.kt

- Added a `compileOnly` dependency onto `kotest` in `selfie-runner-junit5`
- Implemented a `SelfieExtension` that takes an `AbstractProjectConfiguration` in its constructor to enforce project-wide application
- Simplified our coroutine-local implementation to unify the `selfie-runner-junit5` and `selfie-runner-kotest`

Make it easier to mix Kotest and vanilla JUnit5 tests

---

jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieExtension.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotSystemJUnit5.kt

If Kotest only works with the Kotest extension, then the regular JUnit runner can be *a lot* simpler.

Massive simplification to `SnapshotSystemJUnit5`

---

jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/SnapshotSystem.jvm.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SelfieExtension.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SelfieSettingsAPI.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SnapshotSystemKotest.kt
jvm/selfie-runner-kotest/src/jsMain/kotlin/com/diffplug/selfie/kotest/SelfieSettingsAPI.js.kt
jvm/selfie-runner-kotest/src/jvmMain/kotlin/com/diffplug/selfie/kotest/SelfieSettingsAPI.jvm.kt
selfie.dev/src/pages/jvm/kotest.mdx

Settings discoverability is tough to do in a multiplatform way. Since `Kotest` has figured this out with their `AbstractProjectConfiguration` and our users have to explicitly add a `SelfieExtension` there anyway, we might as well tag along for the ride.

Improve `selfie-runner-kotest` settings

---

jvm/example-junit5/src/test/java/selfie/SelfieSettings.java
jvm/gradle/spotless.gradle
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieImplementations.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/coroutines/Coroutines.kt

This is a breaking change unfortunately, but it won't affect end users at all, and the current hierarchy is pretty clearly a mistake. Prep work for
- #221

`Selfie.FooSelfie` to just `FooSelfie`

---

jvm/gradle.properties

Possible to work with older versions, but would take some fiddling.

Kotest 5.4.0 is the oldest we support.

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/coroutines/Coroutines.kt

We only need `DiskStorage` for `toMatchDisk`, so we should be lazy about the error in case the user decides to go with `toBe`. This lets us do:
```kotlin
companion object {
val someString = runBlocking {
cacheSelfie { llmFunctionCall() }.toBe_TODO()
}
}
```

Make DiskStorage errors when running though Kotest lazy, so that we can use `toBe` anywhere.

---

python/selfie-lib/selfie_lib/Literals.py
python/selfie-lib/tests/LiteralString_test.py

- Fixed the issue for "\\u0020" in Literals.py and for LiteralString_test.py. 
- For the third test in test_encode_multi, We have escape_leading_whitespace set to never so I took the leading case out.

LiteralString and LiteralStringTest

---

python/selfie-lib/selfie_lib/Literals.py

Figured out that the reason why Literals wasn't recognizing the string as a multiline string was because I accidentally put the wrong sign for the newline character using "/n" instead of "\n". The tests are working on my end now.

MultiLine string literal fix

---

jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotSystemJUnit5.kt
jvm/selfie-runner-kotest/src/commonMain/kotlin/com/diffplug/selfie/kotest/SnapshotSystemKotest.kt

I ran into an issue where my CI system was deleting my snapshot files. It seems like the readonly flag should apply to any modification selfie might try to make.
I was unable to find any tests that exercise this code so no tests were added.

Do not remove stale snapshot files when readonly is true

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieImplementations.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SourceFile.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralStringTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/SourceFileToBeTest.kt
jvm/selfie-lib/src/jsMain/kotlin/com/diffplug/selfie/SelfieImplementations.js.kt
jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/SelfieImplementations.jvm.kt

For java versions which don't support multiline literals, we now do assertions on multiline strings like this:
```java
toBe("line1",
"line2",
"line3");
```

handle multiline java strings as comma-delimited single-line strings

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt

Users could easily make this on their own, but I've been using it so often it's probably worth upstreaming into the "factory settings".

Added `Selfie.expectSelfie` for easy "multi-asserts"

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt

- This should help debug #370 and other similar issues that may come up

Provide more debugging info when a snapshot gets set multiple times

---

selfie.dev/src/components/Button.tsx
selfie.dev/src/components/HeadingLanguageSelect.tsx
selfie.dev/src/components/IntroText.tsx
selfie.dev/src/pages/_document.tsx

- Disable smooth scroll globally so that using the language switcher is seamless.
- Implement smooth scroll manually for the anchor links in the intro text.

Smooth scroll modifications

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/CacheSelfie.kt

`cacheSelfie` was missing `@JvmOverloads` on the methods with default arguments.

Fix default arguments for `cacheSelfie`.

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieImplementations.kt

so that other testing infrastructure can read from snapshotted values.

`DiskSelfie` now makes the `Snapshot actual` value public

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Mode.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieImplementations.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SnapshotNotEqualErrorMsg.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/SnapshotNotEqualErrorMsgTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InteractiveTest.kt

When a snapshot fails, we now show the first failed line.

Better error messages

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/SelfieImplementations.jvm.kt

I was using the multi-string toBe method (misunderstood, and thought that was to be used for checking multiple facets), and noticed the test would pass no matter what values were expected.

[jvm] fix multi-string toBe

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/EscapeLeadingWhitespace.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/EscapeLeadingWhitespaceTest.kt
python/CHANGELOG.md
python/selfie-lib/selfie_lib/EscapeLeadingWhitespace.py
python/selfie-lib/selfie_lib/__init__.py
python/selfie-lib/tests/EscapeLeadingWhitespace_test.py
python/selfie-lib/uv.lock

A single leading space should not override an otherwise 100% tab-indented file

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/SnapshotFileTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/SnapshotValueReaderTest.kt
jvm/selfie-runner-kotest/src/commonTest/kotlin/com/diffplug/selfie/kotest/HarnessKotest.kt

We were unescaping facets before splitting them up, but we should split them up and *then* unescape.

Fix facet parsing

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/VcrSelfie.kt

Off-by-one in the error message for a VCR key mismatch.

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/ArrayMap.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/ArrayMapTest.kt

Resolves https://github.com/diffplug/selfie/issues/531

Prevent ClassCastException during ArraySet sorting

---

jvm/CHANGELOG.md
jvm/gradle.properties
jvm/gradle/jvm-target.gradle
jvm/selfie-lib/build.gradle
jvm/selfie-runner-junit5/build.gradle
jvm/selfie-runner-kotest/build.gradle

Make sure that we compile to JRE 11.
