diffplug/selfie

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Literals.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/LiteralBooleanTest.kt

- implement bool literal/selfie

Literal: bool literal/selfie

---

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Mode.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/CommentTracker.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Slice.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SnapshotStorage.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
selfie-lib/src/jsMain/kotlin/com/diffplug/selfie/guts/WriteTracker.js.kt
selfie-lib/src/jvmMain/kotlin/com/diffplug/selfie/guts/WriteTracker.jvm.kt
selfie-lib/src/jvmTest/kotlin/testpkg/RecordCallTest.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotFileLayoutJUnit5.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/ReadOnlyTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_ReadOnlyTest.kt

Helper to 
- #80 
in the effort to implement 
- #74

Add `ReadOnlyTest` with better error messages for comments in readonly mode

---

docs/src/pages/jvm/get-started.mdx
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Mode.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InteractiveTest.kt

Helper to 
- #80 
in the effort to implement 
- #74

Improve the snapshot error messages

---

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt

I'd like to add it back someday, but right now our support is far more broken than correct, better off not having it at all I think.

Remove support for Clojure

---

CONTRIBUTING.md
README.md
docs/README.md
docs/public/_redirects
docs/src/components/ButtonList.tsx
docs/src/lib/languageFromPath.ts
gradle/dokka/README.md

- highlight py over go
- fixup GitHub readme's, contributing, etc.

Misc improvements

---

selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_InlineIntTest.kt

So we can use our working single-line there, and stub out into
- #105
- #106

We can ship 1.0 without multiline for Groovy and Scala

---

CHANGELOG.md
README.md
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt
selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotFileTest.kt
selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotReaderTest.kt
selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotValueReaderTest.kt
selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/BinaryTest.kt
undertest-junit5/src/test/kotlin/undertest/junit5/UT_BinaryTest.kt

Add support for binary via base64

---

docs/src/components/Button.tsx
docs/src/components/HeadingPopout.tsx
docs/src/components/NavHeading.tsx

Use an actual `HTMLAnchorElement` for the popouts so the user can see the destination URL in the browser before clicking it.

Popout links

---

docs/src/pages/jvm/advanced.mdx
example-junit5/src/test/java/selfie/SelfieSettings.java

- Update Camera variable names for clarity in the code examples
- Fix a couple of typos
- Opinionated technical language improvement (remove "just" in 1 place)

Improve advanced docs

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt

Improve the error message for duplicate writes to help the user fix their problem

---

jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/BinaryTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/CarriageReturnTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/DiskBasicTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/DiskTodoTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/DuplicateWriteTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/HarnessJUnit.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InlineFacetTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InlineIntTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InlineLongTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/InteractiveTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/MethodLevelGCTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/ParameterizedTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/PrefixAndSubGC.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/ReadOnlyTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/StringLiteralsJavaTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/StringLiteralsKotlinTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/TestMethodVisibility.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/WithinMethodGCTest.kt
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junitvintage/ReadWriteVintageTest.kt

Inspired by improvements in the Kotest harness.

Fixup the JUnit harness

---

jvm/CHANGELOG.md
jvm/gradle/spotless.gradle
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/ArrayMap.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WithinTestGC.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieTestExecutionListener.kt
jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SnapshotSystemJUnit5.kt

More stuff to prepare for coroutines

Improve multithreading correctness / performance

---

.github/workflows/jvm-ci.yml
jvm/README.md
jvm/selfie-runner-junit5/build.gradle
jvm/selfie-runner-junit5/src/test/kotlin/com/diffplug/selfie/junit5/HarnessJUnit.kt
jvm/undertest-junit5-kotest/harness/README.md
jvm/undertest-junit5-kotest/harness/build.gradle
jvm/undertest-junit5-kotest/harness/gradle.properties
jvm/undertest-junit5-kotest/harness/settings.gradle

Move `undertest-junit5-kotest` to a separate project

---

jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt

The `SelfieBound` thing was good for two things:
- it was a nice section in the manual for explaining how threading on test snapshots worked
- in theory, it let you take snapshots in other threads / coroutines
It was a nice section in the docs, but it was extremely error-prone to use because snapshot failures which aren't on the normal thread / coroutine don't show up as test failures. To make it useful, it would need to be something like this:
```kotlin
@Test fun someTest() {
val bound = Selfie.bind()
bound.use {
val thread = new Thread() {
@Override void run() {
bound.expectSelfie(something).toMatchDisk()
}
}
thread.start()
thread.join()
}
}
```
The idea is that the snapshot failure in the new thread would be saved into the `BoundSelfie extends AutoCloseable`, and get rethrown in the …

Remove `SelfieBound` for taking selfies on weird threads and coroutines.

---

jvm/CHANGELOG.md
jvm/example-junit5/src/test/java/selfie/SelfieSettings.java
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/MemoBinary.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/MemoString.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/Selfie.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SelfieImplementations.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/coroutines/Coroutines.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/coroutines/MemoBinarySuspend.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/coroutines/MemoStringSuspend.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SourceFile.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/WriteTracker.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/SourceFileToBeTest.kt
jvm/undertest-junit5-kotest/src/test/kotlin/undertest/junit5/UT_Memoize.kt
jvm/undertest-junit5/src/test/kotlin/undertest/junit5/UT_BinaryTest.kt

Take what we learned from binary memoization and apply it to snapshots of binary data.
- #221

Better binary facets

---

jvm/CHANGELOG.md
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/ArrayMap.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/EscapeLeadingWhitespace.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/Literals.kt
jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/guts/SourceFile.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/EscapeLeadingWhitespaceTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralBooleanTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralIntTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralLongTest.kt
jvm/selfie-lib/src/commonTest/kotlin/com/diffplug/selfie/guts/LiteralStringTest.kt

Don't escape leading whitespace if we can safely avoid it

---

python/selfie-lib/selfie_lib/ArrayMap.py
python/selfie-lib/selfie_lib/IllegalArgumentException.py
python/selfie-lib/selfie_lib/ParseException.py
python/selfie-lib/selfie_lib/PerCharacterEscaper.py
python/selfie-lib/selfie_lib/Snapshot.py
python/selfie-lib/selfie_lib/SnapshotFile.py
python/selfie-lib/selfie_lib/SnapshotReader.py
python/selfie-lib/selfie_lib/SnapshotValue.py
python/selfie-lib/selfie_lib/SnapshotValueReader.py
python/selfie-lib/selfie_lib/__init__.py
python/selfie-lib/tests/SnapshotFile_test.py

SnapshotFile Completed, need to add type hint

SnapshotFile Completed, Type Hint Has Been Added

---

python/selfie-lib/selfie_lib/SelfieImplementations.py

- I merged #352 before it was passing all tests, my bad.

Fix pythong type error introduced in #352

---

python/pytest-selfie/pytest_selfie/plugin.py
python/selfie-lib/selfie_lib/SnapshotSystem.py

Implement assertfailed

---

python/selfie-lib/selfie_lib/Literals.py
python/selfie-lib/selfie_lib/SelfieImplementations.py
python/selfie-lib/selfie_lib/SourceFile.py
python/selfie-lib/selfie_lib/WriteTracker.py
python/selfie-lib/tests/LiteralInt_test.py

- using a string snapshot works great
- using a repr snapshot works great
- switching from one to another was tricky, now fixed

py: fix bugs related to switching a snapshot between string and repr

---

python/selfie-lib/selfie_lib/EscapeLeadingWhitespace.py
python/selfie-lib/selfie_lib/Literals.py
python/selfie-lib/selfie_lib/SourceFile.py
python/selfie-lib/tests/LiteralString_test.py

- implemented https://github.com/diffplug/selfie/issues/382
- fixed some other parts of literal snapshots

py: leading whitespace and literal fixes

---

selfie.dev/src/components/ButtonList.tsx
selfie.dev/src/components/HeadingLanguageSelect.tsx
selfie.dev/src/components/HeadingPopout.tsx
selfie.dev/src/components/Icons/Popout.tsx
selfie.dev/src/components/NavHeading.tsx
selfie.dev/src/components/Navigation/SubNavigation.tsx
selfie.dev/src/lib/languageFromPath.ts

#415 
- change language order in headings
- bring back language-specific dropdowns per-header
- fix a text wrap issue (somewhat)

Website Improvements

---

python/example-pytest-selfie/tests/cache_selfie_test.py
python/example-pytest-selfie/tests/get_started_test.py
python/fullstack-pytest.code-workspace
python/selfie-lib/selfie_lib/CacheSelfie.py
python/selfie-lib/selfie_lib/Lens.py
python/selfie-lib/selfie_lib/LineReader.py
python/selfie-lib/selfie_lib/Snapshot.py
python/selfie-lib/selfie_lib/SnapshotSystem.py
python/selfie-lib/selfie_lib/SnapshotValue.py
python/selfie-lib/selfie_lib/SnapshotValueReader.py
python/selfie-lib/selfie_lib/__init__.py
python/selfie-lib/tests/CompoundLens_test.py
python/selfie-lib/tests/Snapshot_test.py
selfie.dev/src/pages/py/get-started.mdx

The python is sooo close to 1.0, here's the last bit to get it across the finish line.

python: add lens and camera
